// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-CWbilI47Y8uad-ISVcHNXE7k8f1sxEE',
    appId: '1:242339314835:web:eadb524a659987dd0c6166',
    messagingSenderId: '242339314835',
    projectId: 'navkar-jewelquest',
    authDomain: 'navkar-jewelquest.firebaseapp.com',
    storageBucket: 'navkar-jewelquest.appspot.com',
    measurementId: 'G-B403LPTYV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBv6fPzkDCVzEtTvsBU9QvZfSXHY-N3PA',
    appId: '1:242339314835:android:21170811ded9dbb00c6166',
    messagingSenderId: '242339314835',
    projectId: 'navkar-jewelquest',
    storageBucket: 'navkar-jewelquest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbfogxNVRvJa_a7kMtX38REXL5A-9qec',
    appId: '1:242339314835:ios:d2fec66dd05a812f0c6166',
    messagingSenderId: '242339314835',
    projectId: 'navkar-jewelquest',
    storageBucket: 'navkar-jewelquest.appspot.com',
    iosBundleId: 'com.example.navkarJewelQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbfogxNVRvJa_a7kMtX38REXL5A-9qec',
    appId: '1:242339314835:ios:d2fec66dd05a812f0c6166',
    messagingSenderId: '242339314835',
    projectId: 'navkar-jewelquest',
    storageBucket: 'navkar-jewelquest.appspot.com',
    iosBundleId: 'com.example.navkarJewelQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-CWbilI47Y8uad-ISVcHNXE7k8f1sxEE',
    appId: '1:242339314835:web:e2c7ebbd73b826810c6166',
    messagingSenderId: '242339314835',
    projectId: 'navkar-jewelquest',
    authDomain: 'navkar-jewelquest.firebaseapp.com',
    storageBucket: 'navkar-jewelquest.appspot.com',
    measurementId: 'G-PE1JWX51GX',
  );
}
